name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
#   publish:
    # permissions:
    #   id-token: write 
    # uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1

  after-publish:
    # needs: publish
    if: always()
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
    # - name: Check publish status
    #   run: echo "Publish status = ${{ needs.publish.result }}"

    - name: Checkout infra repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/${{ vars.INFRA_REPO }}
        ref: main
        path: infra
        token: ${{ secrets.PAT }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd infra
        npm install

    - name: Run slack-notifier.mjs
      if: always()
      env:
        INTERNAL_REPO_NAME: ${{ vars.INTERNAL_REPO }}
        REF_NAME: ${{ github.ref_name }}
        REPO: ${{ github.repository }}
        DEPLOYMENT_STATUS: ${{ job.status }}
        SLACK_WEBHOOK_TOKEN: ${{ secrets.SLACK_WEBHOOK_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      run: |
        node infra/scripts/slack-notifier.mjs notify-deployment-completion-from-issue

    
